version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    #        working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=.sweetpwd.
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=.mypwd
    ports:
      - "8082:3306"
  website:
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=.mypwd
    container_name: php-7-3-apache
    build:
      context: ./
    volumes:
      - .:/var/www/html/
    ports:
      - 8812:80
    depends_on:
      - mysql
