version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8812:80"
    volumes:
      - ./code:/code
      - ./site.conf/php-docker.local:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - php
  php:
    image: php:7.4.11-fpm-alpine
    volumes:
      - ./code:/code
